version: 2.0
jobs:
  test:
    docker:
      - image: elixir:1.7.4
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y shelltestrunner build-essential
          mix local.hex --force
          ./run_tests.sh ci

workflows:
  version: 2
  commit:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
